### ISSUE TITLE
comparasion

### ISSUE THREAD

**Issue by bAndie91** [fbeline/luneta#28]
hi, i like fuzzy finders.
could you describe in what `luneta` differs or plan to be different from other fuzzy finders, eg. [fzf](https://github.com/junegunn/fzf)? or is it just an exercise project for yourself.
thanks.

**Comment by fbeline** [comment]
Hi,
Nowadays we have a lot of good and consolidated options. It would not be fair to say that it has a "killer" feature that will give everybody a reason to choose Luneta over others. But I can tell you what I want it to be.
I want it to be fast and concise. With a small subset of useful features and no more. Simplicity and accuracy are the goals.
