### ISSUE TITLE
Cannot compile under msys2

### ISSUE THREAD

**Issue by nxuv** [fbeline/luneta#36]
**Describe the bug**
Cannot compile under msys2 (mingw64).

**To Reproduce**
Install packages: `mingw-w64-x86_64-ncurses`, `ncurses`, `ncurses-dev`
Run `dub build -b release --compiler ldc2` or `dub run` in root luneta folder

**Expected behavior**
A succesfully compiled program

**Screenshots**
![image](https://user-images.githubusercontent.com/60989682/181045486-cc62d059-ccea-4a0f-a135-c4475bd50b50.png)

**Desktop (please complete the following information):**
 - OS: Windows 11, **MSYS2**

**Comment by fbeline** [comment]
Hi @al1-ce , unfortunatly right now I have no intention to support mingw.
